"""
sentinel.py – Otonom Sistem Orkestratörü (The CEO).

Bu modül, tüm sistemi (Pipeline, Risk, Bot) tek bir çatı altında yönetir.
"Sentinel", sistemin otonom karar vericisi ve koruyucusudur.

Özellikler:
  - Tek bir Telegram Bot instance'ı yönetir.
  - Pipeline'ı başlatır, durdurur, izler.
  - Risk modunu dinamik olarak değiştirir.
  - Acil durum komutlarını (Force Bet, Shutdown) uygular.
  - Strategy Evolver ile otonom iyileşme sağlar.
  - Otonom Risk Regülasyonu: ROI performansına göre risk modunu otomatik ayarlar.
"""
import asyncio
import signal
import sys
from typing import Optional, Any, Dict
from loguru import logger

from src.reporting.telegram_bot import TelegramBot
from src.pipeline.core import create_default_pipeline, PipelineEngine
from src.system.lifecycle import lifecycle
from src.core.regime_kelly import RegimeKelly, RegimeState
from src.system.container import container
from src.core.event_bus import EventBus
from src.quant.risk.portfolio_manager import PortfolioManager
from src.core.circuit_breaker import CircuitBreakerRegistry
from src.core.strategy_evolver import StrategyEvolver
from src.quant.finance.treasury import TreasuryEngine
from src.quant.analysis.oracle import TheOracle

class Sentinel:
    """
    Sistemin beyni ve yöneticisi.
    """

    def __init__(self, daemon_mode: bool = True):
        self.daemon_mode = daemon_mode
        self.running = False

        # 0. Event Bus (Merkezi Sinir Sistemi)
        self.bus = EventBus()
        self.portfolio_manager = PortfolioManager(self.bus)

        # 0.1 Flash Reaction (Odds Stream Listener)
        from src.core.speed_cache import SpeedCache
        self.speed_cache = SpeedCache()
        # In a real async loop, we'd start a listener task.
        # For now, we subscribe to 'odds_tick' event if generated by ingestion
        self.bus.subscribe("odds_tick", self._handle_flash_reaction)

        # 1. Bot Entegrasyonu
        self.bot = TelegramBot()
        self.bot.set_sentinel(self)
        # Botu event bus'a abone yapabiliriz (daha sonra)

        # 2. Pipeline Hazırlığı
        self.pipeline: PipelineEngine = create_default_pipeline(
            bot_instance=self.bot,
            bus=self.bus
        )

        # 3. Risk Yöneticisi (Shared State via Container)
        # RiskStage ile aynı instance'ı kullandığımızdan emin olmalıyız.
        self.risk_manager = container.get("regime_kelly")
        if self.risk_manager:
            self.bus.subscribe("market_regime_update", self.risk_manager.update_regime)

        self.portfolio_opt = container.get("portfolio_opt")

        # 4. Global Circuit Breaker (Panic Button)
        self.cb_registry = CircuitBreakerRegistry()
        self.system_breaker = self.cb_registry.get_or_create("system_health", preset="api")
        # 1 saatlik soğuma, 3 kritik hata -> OPEN
        self.system_breaker._config.recovery_timeout = 3600.0

        # 5. Treasury & Oracle (Financial & Strategic Command)
        self.treasury = TreasuryEngine()
        self.oracle = TheOracle()

        # 6. Otonom Strateji Evrimi
        self.evolver = StrategyEvolver(population_size=20, elitism_pct=0.1)
        if self.evolver.load_checkpoint():
            logger.info("Sentinel: Strategy Evolver checkpoint yüklendi.")
        else:
            logger.info("Sentinel: Strategy Evolver sıfırdan başlıyor.")

        # Sinyal Yakalama
        if daemon_mode:
            signal.signal(signal.SIGINT, self._handle_sigint)
            signal.signal(signal.SIGTERM, self._handle_sigint)

    def _handle_sigint(self, signum, frame):
        """Ctrl+C yakalayıcı."""
        logger.warning("Sentinel: Kapanma sinyali alındı.")
        self.shutdown()

    async def run(self):
        """Sistemi başlat."""
        logger.info("╔════════════════════════════════════════╗")
        logger.info("║     SENTINEL OTONOM SİSTEM (v2.1)      ║")
        logger.info("╚════════════════════════════════════════╝")

        # System Integrity Check at Startup
        if not await self.system_integrity_check():
            logger.critical("Sentinel: System integrity check failed. Aborting startup.")
            return

        self.running = True

        # Botu başlat
        if self.bot.enabled:
            asyncio.create_task(self.bot.start())
            await self.bot.send_message(
                int(self.bot.token.split(":")[0]) if self.bot.token else 0, # Fallback ID
                "🚀 *Sentinel Başlatıldı.*"
            )

        # Pipeline döngüsü
        cycle_count = 0
        try:
            if self.daemon_mode:
                logger.info("Sentinel: Daemon Modu Aktif. Kontrollü döngü başlıyor.")
                while self.running and not lifecycle.shutdown_event.is_set():
                    cycle_count += 1

                    # 1. Sağlık Kontrolü
                    if not self._check_health():
                        logger.warning("Sentinel: Sistem sağlığı KRİTİK. Devre Kesici AÇIK. 5 dakika bekleniyor.")
                        if self.bot and self.bot.enabled:
                             await self.bot.send_risk_alert("CIRCUIT BREAKER", "Sistem finansal koruma moduna geçti. İşlemler durduruldu.")
                        await asyncio.sleep(300)
                        continue

                    # 2. Pipeline Döngüsü (Tek adım)
                    # Evolver'dan en iyi strateji ağırlıklarını al
                    best_dna = self.evolver.get_best_dna()
                    initial_ctx = {}
                    if best_dna:
                         # DNA'yı context'e enjekte et
                         dna_dict = best_dna.to_dict()
                         # Ensemble Weights'leri ayrıştır
                         weights = {
                             "benter": dna_dict.get("ensemble_weight_poisson", 0.3),
                             "lgbm": dna_dict.get("ensemble_weight_lgbm", 0.35),
                             "lstm": dna_dict.get("ensemble_weight_lstm", 0.2),
                             # Diğer modeller için mapping gerekebilir
                         }
                         initial_ctx["ensemble_weights"] = weights
                         initial_ctx["kelly_fraction"] = dna_dict.get("kelly_fraction", 0.25)

                    cycle_result = await self.pipeline.run_once(initial_context=initial_ctx)

                    # 2.5 Auto Risk Adjustment
                    if cycle_result and "performance_report" in cycle_result:
                        await self.auto_adjust_risk(cycle_result["performance_report"])

                    # 3. Evolver Check (Her 100 döngüde bir evrim)
                    if cycle_count % 100 == 0:
                        await self._run_evolution()

                    # 4. Bekleme
                    await asyncio.sleep(10)
            else:
                if self._check_health():
                    await self.pipeline.run_once()
                else:
                    logger.error("Sistem sağlığı yetersiz. Çalışma iptal edildi.")

        except Exception as e:
            logger.critical(f"Sentinel Critical Error: {e}")
        finally:
            await self.shutdown_async()

    async def system_integrity_check(self) -> bool:
        """Verifies critical components are operational before startup."""
        logger.info("Sentinel: Performing system integrity check...")

        checks = []

        # 1. DB Connection
        db = container.get("db")
        if not db:
            logger.error("Integrity Check: DB manager not found in container.")
            return False
        checks.append("DB Manager: OK")

        # 2. Pipeline Configuration
        if not self.pipeline or not self.pipeline.stages:
            logger.error("Integrity Check: Pipeline stages not configured.")
            return False
        checks.append(f"Pipeline Stages: {len(self.pipeline.stages)} OK")

        # 3. Risk Manager
        if not self.risk_manager:
            logger.warning("Integrity Check: Risk Manager (RegimeKelly) not found. Proceeding with caution.")
        else:
            checks.append("Risk Manager: OK")

        logger.info(f"Integrity Check Passed. Components: {', '.join(checks)}")
        return True

    async def auto_adjust_risk(self, perf_report: Dict[str, Any]):
        """
        Autonomously adjusts risk parameters based on real-time performance (ROI).
        Acts like a Fund Manager regulating exposure.
        """
        roi = perf_report.get("roi", 0.0)

        # Current mode logic (could be stored in state, simplified here)
        # We access risk_manager internal state directly for this autonomous logic
        if not self.risk_manager: return

        current_base_fraction = self.risk_manager._base_fraction
        new_mode = None

        if roi < -0.05: # Drawdown > 5%
            if current_base_fraction > 0.15:
                logger.warning(f"Sentinel: Auto-Risk Adjustment -> Conservative (ROI {roi:.2%})")
                self.set_risk_mode("conservative")
                new_mode = "CONSERVATIVE"
        elif roi > 0.10: # Profit > 10%
            if current_base_fraction < 0.35:
                logger.success(f"Sentinel: Auto-Risk Adjustment -> Aggressive (ROI {roi:.2%})")
                self.set_risk_mode("aggressive")
                new_mode = "AGGRESSIVE"
        elif -0.02 <= roi <= 0.05: # Stable
             if current_base_fraction != 0.25:
                 logger.info(f"Sentinel: Auto-Risk Adjustment -> Normal (ROI {roi:.2%})")
                 self.set_risk_mode("normal")
                 new_mode = "NORMAL"

        if new_mode and self.bot:
             await self.bot.send_message(
                 int(self.bot.token.split(":")[0]) if self.bot.token else 0,
                 f"🤖 *Otonom Risk Ayarı*\nROI: %{roi*100:.2f}\nYeni Mod: *{new_mode}*"
             )

    async def _handle_flash_reaction(self, event: Any):
        """
        Flash Reaction: Reacts to high-velocity odds changes (Dropping Odds).
        Acts as a 'Liquidity Sniper'.
        """
        data = event.data
        match_id = data.get("match_id")
        # Assume data contains z-score or we calculate it here.
        # For simplicity, let's assume ingestion calculated 'z_score'
        z_score = data.get("z_score", 0.0)

        if z_score < -2.0:
            logger.warning(f"⚡ FLASH REACTION: Dropping Odds detected for {match_id} (Z={z_score})")
            # Trigger immediate execution check for this match
            # This bypasses the normal cycle
            if self.pipeline:
                # We need a way to run specific match. Pipeline run_once takes context.
                # Construct a mini-context
                logger.info(f"⚡ Sniping liquidity for {match_id}...")

                # Fetch match data (pseudo-code, in real implementation we fetch from DB/Cache)
                # match_data = self.db.get_match(match_id)

                # For now, just log the intent as we need full match context to run pipeline
                # Ideally: await self.pipeline.run_single_match(match_id)
                pass

    async def _run_evolution(self):
        """Strateji evrimini tetikle."""
        logger.info("Sentinel: Evrim süreci başlıyor...")
        # Geçmiş sonuçları DB'den çekmemiz gerekir
        # Şimdilik basitçe logluyoruz
        # results = self.db.get_recent_results(...)
        # report = self.evolver.evolve(results)
        # if report.improvements:
        #     logger.success(f"Sentinel: Strateji iyileştirildi! {report.improvements}")
        pass

    def _check_health(self) -> bool:
        """Sistemin finansal ve teknik sağlığını kontrol et."""
        if not self.system_breaker.is_available:
            return False

        try:
            # DB'den Ardışık Kayıp Kontrolü
            db = container.get("db")
            if db:
                # Son 10 bahis kontrolü
                try:
                    df = db.query("SELECT status FROM bets WHERE status IN ('won', 'lost') ORDER BY settled_at DESC LIMIT 10")
                    if not df.is_empty():
                        statuses = df["status"].to_list()
                        # Eğer 10 bahis varsa ve hepsi kayıpsa
                        if len(statuses) >= 10 and all(s == 'lost' for s in statuses):
                            raise Exception("10 Ardışık Kayıp! Panic Button devrede.")
                except Exception as db_err:
                     # Tablo yoksa vs yut, sistemi durdurma
                     logger.warning(f"Health check DB uyarısı: {db_err}")

            self.system_breaker._on_success()
            return True
        except Exception as e:
            logger.critical(f"Health Check Failed: {e}")
            self.system_breaker._on_failure(e)
            return False

    def set_risk_mode(self, mode: str) -> str:
        """Risk modunu değiştir (Telegram komutu)."""
        mode = mode.lower()

        # Risk parametrelerini güncelle
        if mode == "aggressive":
            self.risk_manager._base_fraction = 0.35
            self.risk_manager._min_edge = 0.02
        elif mode == "conservative":
            self.risk_manager._base_fraction = 0.15
            self.risk_manager._min_edge = 0.05
        elif mode == "normal":
            self.risk_manager._base_fraction = 0.25
            self.risk_manager._min_edge = 0.03
        else:
            return f"Bilinmeyen mod: {mode}. (aggressive, normal, conservative)"

        logger.info(f"Sentinel: Risk modu '{mode}' olarak ayarlandı.")
        return f"Risk modu güncellendi: *{mode.upper()}*"

    async def force_bet(self, match_id: str, selection: str) -> str:
        """Manuel bahis zorla (Telegram komutu)."""
        logger.warning(f"Sentinel: Manuel bahis isteği -> {match_id} / {selection}")

        # Bu özellik ExecutionStage'e doğrudan emir iletmeyi gerektirir.
        # Şimdilik basitçe logluyoruz, tam implementasyon için
        # Pipeline context'ine "force_orders" listesi eklenmeli.

        # Pipeline context'ine erişimimiz var mı?
        # PipelineEngine her döngüde context'i sıfırlıyor ama persistent bir queue tutabiliriz.
        # Basit bir çözüm: Sentinel'in bir "command_queue"su olur, pipeline bunu okur.

        return f"Manuel emir kuyruğa alındı: {match_id} ({selection})"

    def shutdown(self):
        """Sistemi güvenli kapat."""
        self.running = False
        lifecycle.shutdown_event.set()
        if self.pipeline:
            self.pipeline.running = False
        logger.info("Sentinel: Kapanma prosedürü başlatıldı...")

    async def shutdown_async(self):
        """Async cleanup."""
        if self.bot:
            await self.bot.stop()

        # Persist Treasury State
        if self.treasury:
            self.treasury.save_state()
            logger.info("Sentinel: Treasury state saved.")

        logger.info("Sentinel: Sistem kapandı. Görüşmek üzere.")

if __name__ == "__main__":
    sentinel = Sentinel()
    asyncio.run(sentinel.run())
